version: "3.1"
networks:
  beclosed:
services:
  db:
    image: postgres:9.6.22
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 58000:5432
    networks:
      - beclosed
