// Centralized service exports
export * from "./AppointmentService";
export * from "./ClientService";
export * from "./CommonService";
export * from "./PatientService";
export * from "./AnesthesiaService";
export * from "./BillingService";
export * from "./InventoryService";
export * from "./LabService";
export * from "./LoginService";
export * from "./ReportService";
export * from "./StaffService";
export * from "./MedicationService";
export * from "./TreatmentService";
