// Centralized service exports
export * from "./appointmentService.mjs";
export * from "./clientService.mjs";
export * from "./commonService.mjs";
export * from "./patientService.mjs";
export * from "./anesthesiaService.mjs";
export * from "./billingService.mjs";
export * from "./inventoryService.mjs";
export * from "./labService.mjs";
export * from "./authService.mjs";
export * from "./reportService.mjs";
export * from "./staffService.mjs";
export * from "./medicationService.mjs";
export * from "./treatmentService.mjs";
